---
version: 2
deployment:
  name: demoprojdep
  source-plan: DEM-TES1
release-naming:
  next-version-name: release-2
  applies-to-branches: false
  auto-increment: true
  auto-increment-variables: []
environments:
- test
test:
  triggers: []
  tasks:
  - clean
  - artifact-download:
      artifacts:
      - destination: data/
        name: a1
      description: Download release contents
  - script:
      interpreter: SHELL
      scripts:
      - |-
        echo 'hello world'
        exit 1
      conditions:
      - variable:
          equals:
            dep: 'true'
      description: print
  final-tasks: []
  variables:
    opscan: 'true'
  requirements: []
  notifications: []
---
version: 2
deployment:
  name: demoprojdep
deployment-permissions:
- users:
  - simran
  roles:
  - logged-in
  permissions:
  - view
  - edit
  - view-configuration
  - approve-release
- roles:
  - anonymous
  permissions:
  - view
environment-permissions:
- test:
  - users:
    - simran
    permissions:
    - view
    - edit
    - deploy
    - view-configuration
  - roles:
    - logged-in
    - anonymous
    permissions:
    - view
...
---
version: 2
plan:
  project-key: DEM
  key: TES1
  name: testplan1
stages:
- Default Stage:
    manual: false
    final: false
    jobs:
    - Default Job
Default Job:
  key: JOB1
  tasks:
  - checkout:
      force-clean-build: false
      description: Checkout Default Repository
  - any-task:
      plugin-key: com.atlassian.bamboo.plugins.bamboo-nodejs-plugin:task.builder.npm
      configuration:
        isolatedCache: 'false'
        runtime: Node.js
        command: install
      description: Install
  - any-task:
      plugin-key: com.atlassian.bamboo.plugins.bamboo-nodejs-plugin:task.builder.mocha
      configuration:
        mochaRuntime: node_modules/mocha/bin/mocha
        testFiles: test.mjs
        runtime: Node.js
        parseTestResults: 'true'
      description: check
  - any-task:
      plugin-key: com.atlassian.bamboo.plugins.bamboo-nodejs-plugin:task.builder.node
      configuration:
        runtime: Node.js
        command: index.js
      description: Run apis
  artifacts:
  - name: a1
    pattern:
    - '*.json'
    - '*.txt'
    shared: true
    required: true
  artifact-subscriptions: []
repositories:
- bamboo:
    scope: global
triggers:
- polling:
    period: '180'
branches:
  create: manually
  delete: never
  link-to-jira: true
notifications: []
labels: []
dependencies:
  require-all-stages-passing: false
  enabled-for-branches: true
  block-strategy: none
  plans: []
other:
  concurrent-build-plugin: system-default
  force-stop-build: true
---
version: 2
plan:
  key: DEM-TES1
plan-permissions:
- users:
  - simran
  permissions:
  - view
  - edit
  - build
  - clone
  - admin
  - view-configuration
- roles:
  - logged-in
  - anonymous
  permissions:
  - view
...

