version: 2
plan:
  project-key: DEMO
  name: temp1
  key: TEMP1

stages:
  - First Build Stage:
      jobs: 
        - Build Ship Server

Build Ship Server:
  tasks:
    - script:
        - node index.js
