version: 2
plan:
  project-key: DEMO
  name: temp1
  key: TEMP1

stages:
  - First Build Stage:
      jobs: 
        - Build Ship Server

Build Ship Server:
  tasks:
   - any-task:
      plugin-key: com.atlassian.bamboo.plugins.bamboo-nodejs-plugin:task.builder.npm
      configuration:
        isolatedCache: 'false'
        runtime: Node.js
        command: install
      description: Install
  - any-task:
      plugin-key: com.atlassian.bamboo.plugins.bamboo-nodejs-plugin:task.builder.node
      configuration:
        runtime: Node.js
        command: index.js
      description: check