version: 2
plan:
  project-key: DEMO
  name: temp1
  key: TEMP1

stages:
  - First Build Stage:
      jobs: 
        - Build Ship Server

Build Ship Server:
  tasks:
    - script: 
        interpreter: cmd.exe
        scripts:
          - npm install
          - node index.js